name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        python bayesian.py

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: List Files for Debugging
        run: ls -R 

      - name: Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Docker Image
        run: docker build -t python-app -f python_bayesian_intro/Dockerfile .

      - name: Docker Run
        run: docker run python-app
